name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir lab
            sudo mkdir lab/cloudapplab4
            sudo mv index.html lab/cloudapplab4
            sudo mv README.md lab/cloudapplab4
            cd lab
            sudo yum update -y
            sudo yum install docker -y
            sudo systemctl start docker
            sudo echo -e "FROM httpd:2.4\nCOPY ./cloudapplab4/ /usr/local/apache2/htdocs"
            sudo docker build -t cloudapplab4-image
            sudo docker push Bosunolapo/cloudapplab4-image:version1.0
            sudo docker run --name cloudapplab4-container -p 80:80 -d Bosunolapo/cloudapplab4-image:version1.0
